[options]
http_port = 8071
longpolling_port = 8072

admin_passwd = supersecretmasterpassword123   ; change this to something strong!

db_host = localhost
db_port = 5432
db_user = seaford19
db_password = clinic1234

addons_path = D:/Office/EPR/seaford-clinic-19/custom_addons,D:/Office/EPR/seaford-clinic-19/odoo/addons

log_level = info
logfile = D:/Office/EPR/seaford-clinic-19/odoo.log

limit_time_cpu = 6000
limit_time_real = 12000
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
workers = 0