{
    'name': 'Seaford East medical clinic',
    'description': 'Professional sea-green website theme for Seaford EastMedical Clinic',
    'category': 'Theme/Medical',
    'sequence': 900,
    'version': '19.0.3',
    'depends': ['website'],
    'data': [
        'security/ir.model.access.csv',
        'data/generate_primary_template.xml',
        'data/images.xml',
        'data/team_profiles.xml',
        'views/theme_medical_clinic_templates.xml',
        'views/custom_header.xml',
        'views/team_profile_templates.xml',
        'views/team_profile_backend_views.xml',
        'views/snippets/s_medical_hero.xml',
        'views/snippets/s_services_grid.xml',
        'views/snippets/s_doctor_cards.xml',
        'views/snippets/s_clinic_hours.xml',
        'views/snippets/s_appointment_cta.xml',
        'views/snippets/s_patient_testimonials.xml',
        'views/snippets/s_accreditations.xml',
        'views/snippets/snippets.xml',
        'data/pages/home.xml',
        'data/pages/about.xml',
        'data/pages/services.xml',
        'data/pages/team.xml',
        'data/pages/contact.xml',
        'data/pages/appointments.xml',
        'data/pages/patient_information.xml',
        'data/pages/fees.xml',
        'data/pages/doctors.xml',
        'data/pages/nurses.xml',
        'data/pages/admin_team.xml',
        'data/pages/maternal_child_health.xml',
        'data/pages/womens_mens_health.xml',
        'data/pages/travel.xml',
        'data/pages/medical_procedures.xml',
        'data/pages/health_wellness.xml',
        'data/pages/exercise_physiology.xml',
        'data/pages/allied_health.xml',
        'data/pages/weight_loss.xml',
        'data/pages/patient_links.xml',
        'data/pages/mymedicare_info.xml',
        'data/pages/newsletter.xml',
        'data/pages/career.xml',
        'data/pages/covid_19_information.xml',
        'data/pages/skin_landing_page.xml',
        'data/pages/geriatric_medicine_65_aged_care_resources.xml',
        'data/pages/sexual_health.xml',
        'data/pages/antenatal_care.xml',
        'data/pages/pregnancy_breastfeeding.xml',
        'data/pages/child_health.xml',
        'data/pages/telehealth.xml',
        'data/pages/womens_health.xml',
        'data/pages/mens_health.xml',
        'data/pages/childrens_health.xml',
        'data/pages/chronic_disease_management.xml',
        'data/pages/preventative_health.xml',
        'data/pages/immunisations.xml',
        'data/pages/corporate_flu_clinics.xml',
        'data/pages/iron_infusions.xml',
        'data/pages/shingles_vaccine.xml',
        'data/pages/contraceptive_implant.xml',
        'data/pages/menopause_perimenopause_care.xml',
        'data/pages/fertility_support_family_planning.xml',
        'data/pages/privacy_policy.xml',
        'data/pages/terms_of_service.xml',
        'data/coming_soon_force_update.xml',
        'data/pages/coming_soon.xml',
        'data/menu.xml',
    ],
    'assets': {
        'web._assets_primary_variables': [
            'theme_medical_clinic_east/static/src/scss/primary_variables.scss',
        ],
        'web._assets_secondary_variables': [
            'theme_medical_clinic_east/static/src/scss/secondary_variables.scss',
        ],
        'web.assets_frontend': [
            'theme_medical_clinic_east/static/src/scss/theme.scss',
            'theme_medical_clinic_east/static/src/scss/snippets/*.scss',
        ],
    },
    'images': [
        'static/description/cover.png',
    ],
    'configurator_snippets': {
        'homepage': [],
        # 'homepage': ['s_medical_hero', 's_services_grid', 's_doctor_cards',
        #              's_patient_testimonials', 's_appointment_cta'],
    },
    'new_page_templates': {
        'basic': {
            'clinic_home': ['s_medical_hero', 's_services_grid',
                            's_doctor_cards', 's_appointment_cta'],
        },
    },
    'author': 'Seaford East Medical Clinic',
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
